#!/bin/bash
if [ "$#" == 0 ]
then
docker rm aws-ecs-config-files
  docker run --name=aws-ecs-config-files --volume=/aws-ecs-config-files:/aws-ecs-config-files --tty=false --interactive=false --detach=true aws-ecs-config-files

elif [ "$1" == 'console' ]
then
  docker run --volume=/aws-ecs-config-files:/aws-ecs-config-files --tty=true --interactive=true --detach=false --rm=true aws-ecs-config-files "bundle exec rails c"

elif [ "$1" == 'rspec' ]
then
  docker run --volume=/aws-ecs-config-files:/aws-ecs-config-files --tty=true --interactive=true --detach=false --rm=true aws-ecs-config-files "bundle exec rspec $2 $3 $4 $5 $6 $7 $8 $9"

elif [ "$1" == 'bash' ]
then
  docker run --volume=/aws-ecs-config-files:/aws-ecs-config-files --tty=true --interactive=true --detach=false --rm=true aws-ecs-config-files "/bin/bash"

elif [ "$1" == 'zeus' ]
then
  docker run --volume=/aws-ecs-config-files:/aws-ecs-config-files --tty=true --interactive=true --detach=false --rm=true aws-ecs-config-files "zeus start"

else
  echo "running freeform"
  docker run --name=aws-ecs-config-files-run --volume=/aws-ecs-config-files:/aws-ecs-config-files --tty=true --interactive=true --detach=false --rm=true aws-ecs-config-files "$1 $2 $3 $4 $5 $6 $7 $8 $9"
fi
